// <auto-generated />
using System;
using For_Learning_EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace For_Learning_EF.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220707102130_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("For_Learning_EF.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0ab57f0-82ea-4010-92c8-1a480c7ee977"),
                            Name = "Dep 1"
                        },
                        new
                        {
                            Id = new Guid("c8159cc4-8b93-4549-92bc-5ce24008c77e"),
                            Name = "Dep 2"
                        },
                        new
                        {
                            Id = new Guid("e5373e9f-f56c-48e4-b277-8c88405744fb"),
                            Description = "Young department",
                            Name = "young Dep"
                        });
                });

            modelBuilder.Entity("For_Learning_EF.Models.DepartmentEmployee", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DepartmentId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("DepartmentEmployees");

                    b.HasData(
                        new
                        {
                            DepartmentId = new Guid("f0ab57f0-82ea-4010-92c8-1a480c7ee977"),
                            EmployeeId = new Guid("b4d43fe8-adf2-4523-8e17-5a1d640031a8")
                        },
                        new
                        {
                            DepartmentId = new Guid("f0ab57f0-82ea-4010-92c8-1a480c7ee977"),
                            EmployeeId = new Guid("a927cf54-4e87-4d67-b691-0842ec7e265e")
                        },
                        new
                        {
                            DepartmentId = new Guid("f0ab57f0-82ea-4010-92c8-1a480c7ee977"),
                            EmployeeId = new Guid("950ae4e7-dfff-4b22-9e32-32889e08f8c0")
                        },
                        new
                        {
                            DepartmentId = new Guid("c8159cc4-8b93-4549-92bc-5ce24008c77e"),
                            EmployeeId = new Guid("045dc21a-742e-424b-96e5-494731c62e14")
                        },
                        new
                        {
                            DepartmentId = new Guid("c8159cc4-8b93-4549-92bc-5ce24008c77e"),
                            EmployeeId = new Guid("b6108a5c-c1ec-4596-a0f8-dca2c0091b15")
                        },
                        new
                        {
                            DepartmentId = new Guid("c8159cc4-8b93-4549-92bc-5ce24008c77e"),
                            EmployeeId = new Guid("3f158b22-7515-48e6-83d5-80845c4da485")
                        },
                        new
                        {
                            DepartmentId = new Guid("e5373e9f-f56c-48e4-b277-8c88405744fb"),
                            EmployeeId = new Guid("b4d43fe8-adf2-4523-8e17-5a1d640031a8")
                        },
                        new
                        {
                            DepartmentId = new Guid("e5373e9f-f56c-48e4-b277-8c88405744fb"),
                            EmployeeId = new Guid("a927cf54-4e87-4d67-b691-0842ec7e265e")
                        },
                        new
                        {
                            DepartmentId = new Guid("e5373e9f-f56c-48e4-b277-8c88405744fb"),
                            EmployeeId = new Guid("3f158b22-7515-48e6-83d5-80845c4da485")
                        });
                });

            modelBuilder.Entity("For_Learning_EF.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4d43fe8-adf2-4523-8e17-5a1d640031a8"),
                            Age = 25,
                            CreatedDate = new DateTime(2022, 7, 7, 13, 21, 29, 932, DateTimeKind.Local).AddTicks(5593),
                            FullName = "Director 1"
                        },
                        new
                        {
                            Id = new Guid("a927cf54-4e87-4d67-b691-0842ec7e265e"),
                            Age = 25,
                            CreatedDate = new DateTime(2022, 7, 7, 13, 21, 29, 932, DateTimeKind.Local).AddTicks(5597),
                            FullName = "Employee 1"
                        },
                        new
                        {
                            Id = new Guid("950ae4e7-dfff-4b22-9e32-32889e08f8c0"),
                            Age = 39,
                            CreatedDate = new DateTime(2022, 7, 7, 13, 21, 29, 932, DateTimeKind.Local).AddTicks(5600),
                            FullName = "Employee 2"
                        },
                        new
                        {
                            Id = new Guid("045dc21a-742e-424b-96e5-494731c62e14"),
                            Age = 66,
                            CreatedDate = new DateTime(2022, 7, 7, 13, 21, 29, 932, DateTimeKind.Local).AddTicks(5602),
                            FullName = "Director 2"
                        },
                        new
                        {
                            Id = new Guid("b6108a5c-c1ec-4596-a0f8-dca2c0091b15"),
                            Age = 33,
                            CreatedDate = new DateTime(2022, 7, 7, 13, 21, 29, 932, DateTimeKind.Local).AddTicks(5605),
                            FullName = "Employee 3"
                        },
                        new
                        {
                            Id = new Guid("3f158b22-7515-48e6-83d5-80845c4da485"),
                            Age = 23,
                            CreatedDate = new DateTime(2022, 7, 7, 13, 21, 29, 932, DateTimeKind.Local).AddTicks(5621),
                            FullName = "Employee 4"
                        });
                });

            modelBuilder.Entity("For_Learning_EF.Models.DepartmentEmployee", b =>
                {
                    b.HasOne("For_Learning_EF.Models.Department", "Department")
                        .WithMany("DepartmentEmployee")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("For_Learning_EF.Models.Employee", "Employee")
                        .WithMany("DepartmentEmployee")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("For_Learning_EF.Models.Department", b =>
                {
                    b.Navigation("DepartmentEmployee");
                });

            modelBuilder.Entity("For_Learning_EF.Models.Employee", b =>
                {
                    b.Navigation("DepartmentEmployee");
                });
#pragma warning restore 612, 618
        }
    }
}
