// <auto-generated />
using System;
using For_Learning_EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace For_Learning_EF.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("For_Learning_EF.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f57b376-cbe3-416f-ab94-1af2eab768aa"),
                            Name = "Dep 1"
                        },
                        new
                        {
                            Id = new Guid("d14b8914-9040-4091-8feb-451c04f6fb07"),
                            Name = "Dep 2"
                        },
                        new
                        {
                            Id = new Guid("4db666da-c835-4b2f-8e38-78790be4162d"),
                            Description = "Young department",
                            Name = "young Dep"
                        });
                });

            modelBuilder.Entity("For_Learning_EF.Models.DepartmentEmployee", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DepartmentId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("DepartmentEmployees");

                    b.HasData(
                        new
                        {
                            DepartmentId = new Guid("0f57b376-cbe3-416f-ab94-1af2eab768aa"),
                            EmployeeId = new Guid("41e39972-46a7-473a-8820-d9b5fb3707a4")
                        },
                        new
                        {
                            DepartmentId = new Guid("0f57b376-cbe3-416f-ab94-1af2eab768aa"),
                            EmployeeId = new Guid("be9d8f7f-b019-4fb5-b77c-5c372c30b4f0")
                        },
                        new
                        {
                            DepartmentId = new Guid("0f57b376-cbe3-416f-ab94-1af2eab768aa"),
                            EmployeeId = new Guid("d6fbeb1f-94cf-4fa2-b98c-65721d81eac1")
                        },
                        new
                        {
                            DepartmentId = new Guid("d14b8914-9040-4091-8feb-451c04f6fb07"),
                            EmployeeId = new Guid("c63d0514-7181-437f-ab3e-404f39d1133d")
                        },
                        new
                        {
                            DepartmentId = new Guid("d14b8914-9040-4091-8feb-451c04f6fb07"),
                            EmployeeId = new Guid("7a4924bc-acce-4ac1-9c98-cc573bfac8a4")
                        },
                        new
                        {
                            DepartmentId = new Guid("d14b8914-9040-4091-8feb-451c04f6fb07"),
                            EmployeeId = new Guid("428c08f1-a1aa-4333-8e7e-9a8c508625e5")
                        },
                        new
                        {
                            DepartmentId = new Guid("4db666da-c835-4b2f-8e38-78790be4162d"),
                            EmployeeId = new Guid("41e39972-46a7-473a-8820-d9b5fb3707a4")
                        },
                        new
                        {
                            DepartmentId = new Guid("4db666da-c835-4b2f-8e38-78790be4162d"),
                            EmployeeId = new Guid("be9d8f7f-b019-4fb5-b77c-5c372c30b4f0")
                        },
                        new
                        {
                            DepartmentId = new Guid("4db666da-c835-4b2f-8e38-78790be4162d"),
                            EmployeeId = new Guid("428c08f1-a1aa-4333-8e7e-9a8c508625e5")
                        });
                });

            modelBuilder.Entity("For_Learning_EF.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41e39972-46a7-473a-8820-d9b5fb3707a4"),
                            Age = 25,
                            CreatedDate = new DateTime(2022, 7, 7, 13, 33, 17, 855, DateTimeKind.Local).AddTicks(2879),
                            FullName = "Director 1"
                        },
                        new
                        {
                            Id = new Guid("be9d8f7f-b019-4fb5-b77c-5c372c30b4f0"),
                            Age = 25,
                            CreatedDate = new DateTime(2022, 7, 7, 13, 33, 17, 855, DateTimeKind.Local).AddTicks(2912),
                            FullName = "Employee 1"
                        },
                        new
                        {
                            Id = new Guid("d6fbeb1f-94cf-4fa2-b98c-65721d81eac1"),
                            Age = 39,
                            CreatedDate = new DateTime(2022, 7, 7, 13, 33, 17, 855, DateTimeKind.Local).AddTicks(2914),
                            FullName = "Employee 2"
                        },
                        new
                        {
                            Id = new Guid("c63d0514-7181-437f-ab3e-404f39d1133d"),
                            Age = 66,
                            CreatedDate = new DateTime(2022, 7, 7, 13, 33, 17, 855, DateTimeKind.Local).AddTicks(2924),
                            FullName = "Director 2"
                        },
                        new
                        {
                            Id = new Guid("7a4924bc-acce-4ac1-9c98-cc573bfac8a4"),
                            Age = 33,
                            CreatedDate = new DateTime(2022, 7, 7, 13, 33, 17, 855, DateTimeKind.Local).AddTicks(2926),
                            FullName = "Employee 3"
                        },
                        new
                        {
                            Id = new Guid("428c08f1-a1aa-4333-8e7e-9a8c508625e5"),
                            Age = 23,
                            CreatedDate = new DateTime(2022, 7, 7, 13, 33, 17, 855, DateTimeKind.Local).AddTicks(2931),
                            FullName = "Employee 4"
                        });
                });

            modelBuilder.Entity("For_Learning_EF.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("For_Learning_EF.Models.DepartmentEmployee", b =>
                {
                    b.HasOne("For_Learning_EF.Models.Department", "Department")
                        .WithMany("DepartmentEmployee")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("For_Learning_EF.Models.Employee", "Employee")
                        .WithMany("DepartmentEmployee")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("For_Learning_EF.Models.Department", b =>
                {
                    b.Navigation("DepartmentEmployee");
                });

            modelBuilder.Entity("For_Learning_EF.Models.Employee", b =>
                {
                    b.Navigation("DepartmentEmployee");
                });
#pragma warning restore 612, 618
        }
    }
}
